### ISSUE TITLE
json ERORR in sever

### ISSUE THREAD

**Issue by shayankebriti** [mosajjal/HotgramSOCKS#1]
```
Traceback (most recent call last):
  File "/home/shayan/proxy.py", line 38, in <module>
    decoded_proxy = get_proxy(IV, KEY, URL)
  File "/home/shayan/proxy.py", line 31, in get_proxy
    b64_encrypted_proxy = json.loads(response).get("data")[0]
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

i got this error when i run it in pythonanywhere.com server,
but in my local linux it works great,

thank you :+1:

**Comment by mosajjal** [comment]
You can verify the decoded JSON before starting to parse it. I'll try to make it more debuggable if I get the time.
